apiVersion: v1
kind: Service
metadata:
  name:  hdevopz-rtp-service
  namespace: hdevopz
spec:
  type: NodePort
  selector:
    app: hdevopz-rtp
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000
